/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_qat_InternalJNI */

#ifndef _Included_com_intel_qat_InternalJNI
#define _Included_com_intel_qat_InternalJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    initFieldIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_qat_InternalJNI_initFieldIDs
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    setupSession
 * Signature: (Lcom/intel/qat/QatZipper;IIIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_intel_qat_InternalJNI_setupSession
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    maxCompressedLength
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_com_intel_qat_InternalJNI_maxCompressedLength
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    compressBytesBytes
 * Signature: (I[BII[BIII)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_qat_InternalJNI_compressBytesBytes
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    compressBytesBuffer
 * Signature: (I[BIILjava/nio/ByteBuffer;III)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_qat_InternalJNI_compressBytesBuffer
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jobject, jint, jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    compressBufferBytes
 * Signature: (ILjava/nio/ByteBuffer;II[BIII)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_qat_InternalJNI_compressBufferBytes
  (JNIEnv *, jclass, jint, jobject, jint, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    compressBufferBuffer
 * Signature: (ILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;III)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_qat_InternalJNI_compressBufferBuffer
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    compressFullBytesBytes
 * Signature: (I[BIII[BII[III)I
 */
JNIEXPORT jint JNICALL Java_com_intel_qat_InternalJNI_compressFullBytesBytes
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jint, jbyteArray, jint, jint, jintArray, jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    decompressBytesBytes
 * Signature: (I[BII[BIII)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_qat_InternalJNI_decompressBytesBytes
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    decompressBytesBuffer
 * Signature: (I[BIILjava/nio/ByteBuffer;III)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_qat_InternalJNI_decompressBytesBuffer
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jobject, jint, jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    decompressBufferBytes
 * Signature: (ILjava/nio/ByteBuffer;II[BIII)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_qat_InternalJNI_decompressBufferBytes
  (JNIEnv *, jclass, jint, jobject, jint, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    decompressBufferBuffer
 * Signature: (ILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;III)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_qat_InternalJNI_decompressBufferBuffer
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    decompressFullBytesBytes
 * Signature: (I[BII[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_intel_qat_InternalJNI_decompressFullBytesBytes
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    zstdGetSeqProdFunction
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intel_qat_InternalJNI_zstdGetSeqProdFunction
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    zstdCreateSeqProdState
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intel_qat_InternalJNI_zstdCreateSeqProdState
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    zstdFreeSeqProdState
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_qat_InternalJNI_zstdFreeSeqProdState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    teardown
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_intel_qat_InternalJNI_teardown
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    setLogLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_intel_qat_InternalJNI_setLogLevel
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif

