/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_qat_InternalJNI */

#ifndef _Included_com_intel_qat_InternalJNI
#define _Included_com_intel_qat_InternalJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    setup
 * Signature: (Lcom/intel/qat/QatZipper;III)V
 */
JNIEXPORT void JNICALL Java_com_intel_qat_InternalJNI_setup(JNIEnv *, jclass,
                                                            jobject, jint, jint,
                                                            jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    maxCompressedSize
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_intel_qat_InternalJNI_maxCompressedSize(
    JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    compressByteArray
 * Signature: (J[BII[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_intel_qat_InternalJNI_compressByteArray(
    JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jint, jint,
    jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    decompressByteArray
 * Signature: (J[BII[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_intel_qat_InternalJNI_decompressByteArray(
    JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jint, jint,
    jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    compressByteBuffer
 * Signature: (JLjava/nio/ByteBuffer;[BII[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_intel_qat_InternalJNI_compressByteBuffer(
    JNIEnv *, jclass, jlong, jobject, jbyteArray, jint, jint, jbyteArray, jint,
    jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    decompressByteBuffer
 * Signature: (JLjava/nio/ByteBuffer;[BII[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_intel_qat_InternalJNI_decompressByteBuffer(
    JNIEnv *, jclass, jlong, jobject, jbyteArray, jint, jint, jbyteArray, jint,
    jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    compressDirectByteBuffer
 * Signature: (JLjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;III)I
 */
JNIEXPORT jint JNICALL Java_com_intel_qat_InternalJNI_compressDirectByteBuffer(
    JNIEnv *, jclass, jlong, jobject, jint, jint, jobject, jint, jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    decompressDirectByteBuffer
 * Signature: (JLjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;III)I
 */
JNIEXPORT jint JNICALL
Java_com_intel_qat_InternalJNI_decompressDirectByteBuffer(JNIEnv *, jclass,
                                                          jlong, jobject, jint,
                                                          jint, jobject, jint,
                                                          jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    compressDirectByteBufferSrc
 * Signature: (JLjava/nio/ByteBuffer;II[BIII)I
 */
JNIEXPORT jint JNICALL
Java_com_intel_qat_InternalJNI_compressDirectByteBufferSrc(JNIEnv *, jclass,
                                                           jlong, jobject, jint,
                                                           jint, jbyteArray,
                                                           jint, jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    decompressDirectByteBufferSrc
 * Signature: (JLjava/nio/ByteBuffer;II[BIII)I
 */
JNIEXPORT jint JNICALL
Java_com_intel_qat_InternalJNI_decompressDirectByteBufferSrc(
    JNIEnv *, jclass, jlong, jobject, jint, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    compressDirectByteBufferDst
 * Signature: (JLjava/nio/ByteBuffer;[BIILjava/nio/ByteBuffer;III)I
 */
JNIEXPORT jint JNICALL
Java_com_intel_qat_InternalJNI_compressDirectByteBufferDst(JNIEnv *, jclass,
                                                           jlong, jobject,
                                                           jbyteArray, jint,
                                                           jint, jobject, jint,
                                                           jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    decompressDirectByteBufferDst
 * Signature: (JLjava/nio/ByteBuffer;[BIILjava/nio/ByteBuffer;III)I
 */
JNIEXPORT jint JNICALL
Java_com_intel_qat_InternalJNI_decompressDirectByteBufferDst(JNIEnv *, jclass,
                                                             jlong, jobject,
                                                             jbyteArray, jint,
                                                             jint, jobject,
                                                             jint, jint, jint);

/*
 * Class:     com_intel_qat_InternalJNI
 * Method:    teardown
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_qat_InternalJNI_teardown(JNIEnv *, jclass,
                                                               jlong);

#ifdef __cplusplus
}
#endif
#endif
